# Generated by Django 4.2.6 on 2025-01-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KatagoriSurat',
        ),
        migrations.RenameField(
            model_name='dbsurat',
            old_name='kepada',
            new_name='jam',
        ),
        migrations.RenameField(
            model_name='dbsurat',
            old_name='no_surat',
            new_name='tentang',
        ),
        migrations.RenameField(
            model_name='dbsurat',
            old_name='kategori',
            new_name='trak',
        ),
        migrations.RemoveField(
            model_name='dbsurat',
            name='perihal',
        ),
    ]
