# Generated by Django 4.2.6 on 2025-01-08 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0002_delete_katagorisurat_rename_kepada_dbsurat_jam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsurat',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
