# Generated by Django 4.2.6 on 2025-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0003_dbsurat_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tgl', models.DateField()),
                ('dari', models.CharField(max_length=30)),
                ('untuk', models.CharField(max_length=30)),
                ('keterangan', models.CharField(max_length=100)),
                ('pemasukan', models.CharField(max_length=200)),
                ('pengeluaran', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Kas',
            },
        ),
    ]
