# Generated by Django 4.2.6 on 2025-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0005_alter_kas_dari_alter_kas_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kas',
            name='dari',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='keterangan',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='pemasukan',
            field=models.IntegerField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='pengeluaran',
            field=models.IntegerField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='untuk',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
    ]
