# Generated by Django 4.2.6 on 2025-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0006_alter_kas_dari_alter_kas_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kas',
            name='pemasukan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='pengeluaran',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
