# Generated by Django 4.2.6 on 2025-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0008_remove_dbsurat_tentang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kas',
        ),
        migrations.AddField(
            model_name='dbsurat',
            name='pemasukan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dbsurat',
            name='pengeluaran',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
