# Generated by Django 4.2.6 on 2025-01-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_surat_app', '0009_delete_kas_dbsurat_pemasukan_dbsurat_pengeluaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsurat',
            name='surat',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='dbsurat',
            name='trak',
            field=models.CharField(max_length=35),
        ),
    ]
